import {
  Condominio,
  UserProfile,
  Unidade,
  LancamentoFinanceiro,
  Manutencao,
  Comunicado,
  Documento,
  Assembleia,
  AtividadeRecente,
  ResumoFinanceiroDashboard,
  ResumoManutencaoDashboard,
} from '../types';

export const mockCondominio: Condominio = {
  id: 'cond-01',
  nome: 'Condomínio Residencial',
  cnpj: '12.345.678/0001-90',
  endereco: 'Av. das Palmeiras, 1420 - Jardim América',
  cidade: 'São Paulo',
  estado: 'SP',
  cep: '01420-001',
  totalUnidades: 48,
  sindicoNome: 'Roberto Almeida',
  telefoneContato: '(11) 98765-4321',
  emailContato: 'administracao@condominio.com.br',
};

export const mockUsuarios: UserProfile[] = [
  {
    id: 'user-admin-01',
    email: 'admin@condominio.com.br',
    nome: 'Roberto Almeida',
    role: 'admin',
    cargo: 'Síndico Geral',
    telefone: '(11) 98765-4321',
    condominioId: 'cond-01',
    ativo: true,
    criadoEm: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user-morador-01',
    email: 'morador@condominio.com.br',
    nome: 'Carlos Eduardo Silva',
    role: 'morador',
    cargo: 'Morador / Proprietário',
    telefone: '(11) 97654-3210',
    condominioId: 'cond-01',
    unidadeId: 'und-102',
    unidadeNumero: '102 - Bloco A',
    ativo: true,
    criadoEm: '2025-02-15T14:30:00Z',
  },
  {
    id: 'user-morador-02',
    email: 'mariana.costa@email.com',
    nome: 'Mariana Costa',
    role: 'morador',
    cargo: 'Moradora / Inquilina',
    telefone: '(11) 96543-2109',
    condominioId: 'cond-01',
    unidadeId: 'und-204',
    unidadeNumero: '204 - Bloco B',
    ativo: true,
    criadoEm: '2025-03-01T09:15:00Z',
  },
];

export const mockUnidades: Unidade[] = [
  {
    id: 'und-101',
    condominioId: 'cond-01',
    numero: '101',
    bloco: 'Bloco A',
    andar: 1,
    metragem: 82.5,
    fracaoIdeal: 0.020833,
    situacao: 'OCUPADA_PROPRIETARIO',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'Fernando Mendes',
    proprietarioEmail: 'fernando.mendes@email.com',
    proprietarioTelefone: '(11) 98111-2233',
    moradorNome: 'Fernando Mendes',
    moradorEmail: 'fernando.mendes@email.com',
    moradorTelefone: '(11) 98111-2233',
    vagasGaragem: 'G-12 (Piso 1)',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-10T00:00:00Z',
  },
  {
    id: 'und-102',
    condominioId: 'cond-01',
    numero: '102',
    bloco: 'Bloco A',
    andar: 1,
    metragem: 82.5,
    fracaoIdeal: 0.020833,
    situacao: 'OCUPADA_PROPRIETARIO',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'Carlos Eduardo Silva',
    proprietarioEmail: 'morador@condominio.com.br',
    proprietarioTelefone: '(11) 97654-3210',
    moradorNome: 'Carlos Eduardo Silva',
    moradorEmail: 'morador@condominio.com.br',
    moradorTelefone: '(11) 97654-3210',
    vagasGaragem: 'G-13 (Piso 1)',
    observacoes: 'Autorizado acesso de prestadores de serviço.',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-15T00:00:00Z',
  },
  {
    id: 'und-103',
    condominioId: 'cond-01',
    numero: '103',
    bloco: 'Bloco A',
    andar: 1,
    metragem: 75.0,
    fracaoIdeal: 0.018900,
    situacao: 'OCUPADA_INQUILINO',
    situacaoFinanceira: 'PENDENTE',
    proprietarioNome: 'Juliana Paes Castro',
    proprietarioEmail: 'juliana.castro@email.com',
    proprietarioTelefone: '(11) 97222-3344',
    moradorNome: 'Lucas Andrade',
    moradorEmail: 'lucas.andrade@email.com',
    moradorTelefone: '(11) 97333-4455',
    vagasGaragem: 'G-14 (Piso 1)',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-18T00:00:00Z',
  },
  {
    id: 'und-104',
    condominioId: 'cond-01',
    numero: '104',
    bloco: 'Bloco A',
    andar: 1,
    metragem: 75.0,
    fracaoIdeal: 0.018900,
    situacao: 'OCUPADA_PROPRIETARIO',
    situacaoFinanceira: 'INADIMPLENTE',
    proprietarioNome: 'Rodrigo Botelho',
    proprietarioEmail: 'rodrigo.botelho@email.com',
    proprietarioTelefone: '(11) 97444-5566',
    moradorNome: 'Rodrigo Botelho',
    moradorEmail: 'rodrigo.botelho@email.com',
    moradorTelefone: '(11) 97444-5566',
    vagasGaragem: 'G-15 (Piso 1)',
    observacoes: 'Notificação enviada referente a 2 cotas em atraso.',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-25T00:00:00Z',
  },
  {
    id: 'und-201',
    condominioId: 'cond-01',
    numero: '201',
    bloco: 'Bloco B',
    andar: 2,
    metragem: 90.0,
    fracaoIdeal: 0.022727,
    situacao: 'OCUPADA_PROPRIETARIO',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'Patrícia Lima',
    proprietarioEmail: 'patricia.lima@email.com',
    proprietarioTelefone: '(11) 97555-6677',
    moradorNome: 'Patrícia Lima',
    moradorEmail: 'patricia.lima@email.com',
    moradorTelefone: '(11) 97555-6677',
    vagasGaragem: 'G-21 (Piso 2)',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-12T00:00:00Z',
  },
  {
    id: 'und-204',
    condominioId: 'cond-01',
    numero: '204',
    bloco: 'Bloco B',
    andar: 2,
    metragem: 82.5,
    fracaoIdeal: 0.020833,
    situacao: 'OCUPADA_INQUILINO',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'Renato Guimarães',
    proprietarioEmail: 'renato.guimaraes@email.com',
    proprietarioTelefone: '(11) 97666-7788',
    moradorNome: 'Mariana Costa',
    moradorEmail: 'mariana.costa@email.com',
    moradorTelefone: '(11) 96543-2109',
    vagasGaragem: 'G-24 (Piso 2)',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-20T00:00:00Z',
  },
  {
    id: 'und-301',
    condominioId: 'cond-01',
    numero: '301',
    bloco: 'Bloco B',
    andar: 3,
    metragem: 82.5,
    fracaoIdeal: 0.020833,
    situacao: 'EM_REFORMA',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'André Queiroz',
    proprietarioEmail: 'andre.queiroz@email.com',
    proprietarioTelefone: '(11) 97777-8899',
    vagasGaragem: 'G-31 (Piso 2)',
    observacoes: 'Reforma com RRT aprovada até 30/03/2026.',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-28T00:00:00Z',
  },
  {
    id: 'und-302',
    condominioId: 'cond-01',
    numero: '302',
    bloco: 'Bloco B',
    andar: 3,
    metragem: 75.0,
    fracaoIdeal: 0.018900,
    situacao: 'DESOCUPADA',
    situacaoFinanceira: 'EM_DIA',
    proprietarioNome: 'Camila Vasconcelos',
    proprietarioEmail: 'camila.vasconcelos@email.com',
    proprietarioTelefone: '(11) 97888-9900',
    vagasGaragem: 'G-32 (Piso 2)',
    criadoEm: '2025-01-01T00:00:00Z',
    atualizadoEm: '2026-02-01T00:00:00Z',
  },
];

export const mockLancamentosFinanceiros: LancamentoFinanceiro[] = [
  {
    id: 'lan-01',
    condominioId: 'cond-01',
    unidadeId: 'und-101',
    unidadeNumero: '101 - Bloco A',
    tipo: 'RECEITA',
    categoria: 'TAXA_CONDOMINIAL',
    descricao: 'Cota Condominial - Março/2026',
    valor: 780.0,
    dataVencimento: '2026-03-10',
    dataPagamento: '2026-03-05',
    status: 'PAGO',
    criadoEm: '2026-02-25T08:00:00Z',
  },
  {
    id: 'lan-02',
    condominioId: 'cond-01',
    unidadeId: 'und-102',
    unidadeNumero: '102 - Bloco A',
    tipo: 'RECEITA',
    categoria: 'TAXA_CONDOMINIAL',
    descricao: 'Cota Condominial - Março/2026',
    valor: 780.0,
    dataVencimento: '2026-03-10',
    status: 'PENDENTE',
    observacoes: 'Boleto bancário gerado (Linha digitável disponível)',
    criadoEm: '2026-02-25T08:00:00Z',
  },
  {
    id: 'lan-02-prev',
    condominioId: 'cond-01',
    unidadeId: 'und-102',
    unidadeNumero: '102 - Bloco A',
    tipo: 'RECEITA',
    categoria: 'TAXA_CONDOMINIAL',
    descricao: 'Cota Condominial - Fevereiro/2026',
    valor: 780.0,
    dataVencimento: '2026-02-10',
    dataPagamento: '2026-02-08',
    status: 'PAGO',
    criadoEm: '2026-01-25T08:00:00Z',
  },
  {
    id: 'lan-03',
    condominioId: 'cond-01',
    unidadeId: 'und-104',
    unidadeNumero: '104 - Bloco A',
    tipo: 'RECEITA',
    categoria: 'TAXA_CONDOMINIAL',
    descricao: 'Cota Condominial - Fevereiro/2026',
    valor: 780.0,
    dataVencimento: '2026-02-10',
    status: 'ATRASADO',
    observacoes: 'Cobrança em 2ª via enviada ao proprietário.',
    criadoEm: '2026-01-25T08:00:00Z',
  },
  {
    id: 'lan-04',
    condominioId: 'cond-01',
    tipo: 'DESPESA',
    categoria: 'ENERGIA_ELETRICA',
    descricao: 'Conta de Energia Enel (Áreas Comuns)',
    valor: 2450.8,
    dataVencimento: '2026-03-08',
    status: 'PENDENTE',
    criadoEm: '2026-02-28T10:00:00Z',
  },
  {
    id: 'lan-05',
    condominioId: 'cond-01',
    tipo: 'DESPESA',
    categoria: 'MANUTENCAO',
    descricao: 'Manutenção Mensal dos Elevadores Atlas Schindler',
    valor: 1890.0,
    dataVencimento: '2026-03-15',
    status: 'PENDENTE',
    criadoEm: '2026-03-01T09:00:00Z',
  },
  {
    id: 'lan-06',
    condominioId: 'cond-01',
    tipo: 'DESPESA',
    categoria: 'SEGURANCA',
    descricao: 'Portaria Remota e Monitoramento 24h',
    valor: 4300.0,
    dataVencimento: '2026-03-05',
    dataPagamento: '2026-03-04',
    status: 'PAGO',
    criadoEm: '2026-02-20T11:00:00Z',
  },
  {
    id: 'lan-07',
    condominioId: 'cond-01',
    tipo: 'DESPESA',
    categoria: 'LIMPEZA_CONSERVACAO',
    descricao: 'Produtos de Limpeza e Conservação Mensal',
    valor: 640.5,
    dataVencimento: '2026-03-02',
    dataPagamento: '2026-03-02',
    status: 'PAGO',
    criadoEm: '2026-02-22T14:00:00Z',
  },
  {
    id: 'lan-08',
    condominioId: 'cond-01',
    tipo: 'DESPESA',
    categoria: 'SEGURO',
    descricao: 'Seguro Predial Obrigatório (Parcela 3/12)',
    valor: 820.0,
    dataVencimento: '2026-03-12',
    status: 'PENDENTE',
    criadoEm: '2026-02-26T16:00:00Z',
  },
];

export const mockManutencoes: Manutencao[] = [
  {
    id: 'man-01',
    condominioId: 'cond-01',
    titulo: 'Revisão e regulagem do portão de veículos 01',
    descricao: 'Portão principal de veículos apresentando lentidão no fechamento e ruído no motor.',
    local: 'GARAGEM',
    localDescricao: 'Portão social de entrada de carros',
    prioridade: 'ALTA',
    status: 'EM_ANDAMENTO',
    solicitanteId: 'user-admin-01',
    solicitanteNome: 'Roberto Almeida (Síndico)',
    responsavelNome: 'Serralheria & Motores Silva',
    custoEstimado: 450.0,
    dataAbertura: '2026-03-01T10:00:00Z',
    dataPrevisao: '2026-03-04',
    historico: [
      {
        data: '2026-03-01T10:00:00Z',
        autor: 'Roberto Almeida',
        mensagem: 'Chamado aberto após relato da portaria.',
      },
      {
        data: '2026-03-01T15:30:00Z',
        autor: 'Roberto Almeida',
        mensagem: 'Técnico realizou vistoria e solicitou troca das roldanas e lubrificação da cremalheira.',
      },
    ],
  },
  {
    id: 'man-02',
    condominioId: 'cond-01',
    titulo: 'Lâmpada queimada no hall do 2º andar - Bloco B',
    descricao: 'Duas lâmpadas de LED do corredor estão piscando/queimadas.',
    local: 'AREA_COMUM',
    localDescricao: 'Hall do 2º andar, em frente ao elevador social',
    prioridade: 'BAIXA',
    status: 'ABERTA',
    solicitanteId: 'user-morador-02',
    solicitanteNome: 'Mariana Costa',
    solicitanteUnidade: '204 - Bloco B',
    dataAbertura: '2026-03-01T12:45:00Z',
    dataPrevisao: '2026-03-03',
  },
  {
    id: 'man-03',
    condominioId: 'cond-01',
    titulo: 'Higienização e desinfecção semestral das Caixas d\'Água',
    descricao: 'Limpeza periódica obrigatória com emissão de laudo bacteriológico de potabilidade.',
    local: 'AREA_COMUM',
    localDescricao: 'Reservatórios Superior e Inferior',
    prioridade: 'MEDIA',
    status: 'CONCLUIDA',
    solicitanteId: 'user-admin-01',
    solicitanteNome: 'Roberto Almeida (Síndico)',
    responsavelNome: 'HidroLimpa Serviços Ambientais',
    custoEstimado: 1800.0,
    custoReal: 1800.0,
    dataAbertura: '2026-02-10T08:00:00Z',
    dataConclusao: '2026-02-20T17:00:00Z',
  },
];

export const mockComunicados: Comunicado[] = [
  {
    id: 'com-01',
    condominioId: 'cond-01',
    titulo: 'Dedetização e Desratização das Áreas Comuns',
    conteudo:
      'Informamos que no próximo sábado, dia 07/03/2026, a partir das 08h30, será realizada a aplicação periódica de desinsetização e desratização em todas as áreas externas, garagens, lixeiras e caixas de gordura. Solicitamos atenção especial com animais de estimação e crianças.',
    categoria: 'GERAL',
    importante: true,
    autorId: 'user-admin-01',
    autorNome: 'Administração / Síndico',
    dataPublicacao: '2026-03-01T09:00:00Z',
    leiturasConfirmadas: 34,
  },
  {
    id: 'com-02',
    condominioId: 'cond-01',
    titulo: 'Campanha de Conscientização: Descarte Correto de Lixo',
    conteudo:
      'Lembramos a todos os moradores que o lixo reciclável deve ser separado do lixo orgânico antes de ser colocado nos recipientes da lixeira principal. Nunca descarte caixas de papelão sem desmontá-las previamente.',
    categoria: 'GERAL',
    importante: false,
    autorId: 'user-admin-01',
    autorNome: 'Administração / Síndico',
    dataPublicacao: '2026-02-24T14:00:00Z',
    leiturasConfirmadas: 41,
  },
  {
    id: 'com-03',
    condominioId: 'cond-01',
    titulo: 'Convocação para Assembleia Geral Ordinária (AGO 2026)',
    conteudo:
      'Ficam convocados todos os senhores condôminos para a Assembleia Geral Ordinária que realizar-se-á no dia 25/03/2026, às 19h00 em primeira convocação e às 19h30 em segunda convocação.',
    categoria: 'REUNIAO',
    importante: true,
    autorId: 'user-admin-01',
    autorNome: 'Roberto Almeida (Síndico)',
    dataPublicacao: '2026-02-20T10:30:00Z',
    leiturasConfirmadas: 46,
  },
];

export const mockDocumentos: Documento[] = [
  {
    id: 'doc-01',
    condominioId: 'cond-01',
    titulo: 'Convenção do Condomínio',
    descricao: 'Documento registrado em cartório contendo as normas estruturais e constitucionais do condomínio.',
    categoria: 'CONVENCAO',
    arquivoUrl: '#',
    formato: 'PDF',
    tamanhoKb: 2450,
    visivelParaMoradores: true,
    criadoPor: 'Administração',
    criadoEm: '2025-01-10T10:00:00Z',
  },
  {
    id: 'doc-02',
    condominioId: 'cond-01',
    titulo: 'Regimento Interno Atualizado',
    descricao: 'Normas de convivência, horários de silêncio, uso de áreas e regras gerais.',
    categoria: 'REGIMENTO_INTERNO',
    arquivoUrl: '#',
    formato: 'PDF',
    tamanhoKb: 1120,
    visivelParaMoradores: true,
    criadoPor: 'Administração',
    criadoEm: '2025-01-15T11:00:00Z',
  },
  {
    id: 'doc-03',
    condominioId: 'cond-01',
    titulo: 'Ata da Assembleia Geral Ordinária - 2025',
    descricao: 'Ata da reunião de prestação de contas do exercício anterior devidamente assinada.',
    categoria: 'ATA_ASSEMBLEIA',
    arquivoUrl: '#',
    formato: 'PDF',
    tamanhoKb: 890,
    visivelParaMoradores: true,
    criadoPor: 'Administração',
    criadoEm: '2025-03-28T16:00:00Z',
  },
  {
    id: 'doc-04',
    condominioId: 'cond-01',
    titulo: 'Balancete Financeiro e Demonstrativo - Fevereiro/2026',
    descricao: 'Detalhamento das receitas auferidas e despesas liquidadas com parecer do conselho fiscal.',
    categoria: 'PRESTACAO_CONTAS',
    arquivoUrl: '#',
    formato: 'PDF',
    tamanhoKb: 1580,
    visivelParaMoradores: true,
    criadoPor: 'Administração',
    criadoEm: '2026-03-01T09:00:00Z',
  },
  {
    id: 'doc-05',
    condominioId: 'cond-01',
    titulo: 'Apólice do Seguro Predial Contra Incêndio e Danos Elétricos',
    descricao: 'Vigência 2026/2027 emitida pela Seguradora Porto Seguro.',
    categoria: 'SEGUROS_LAUDOS',
    arquivoUrl: '#',
    formato: 'PDF',
    tamanhoKb: 1740,
    visivelParaMoradores: true,
    criadoPor: 'Administração',
    criadoEm: '2026-01-05T14:00:00Z',
  },
];

export const mockAssembleias: Assembleia[] = [
  {
    id: 'ass-01',
    condominioId: 'cond-01',
    titulo: 'Assembleia Geral Ordinária (AGO) - Exercício 2026',
    tipo: 'AGO',
    status: 'AGENDADA',
    dataHoraPrimeiraConvocacao: '2026-03-25T19:00:00',
    dataHoraSegundaConvocacao: '2026-03-25T19:30:00',
    local: 'Salão Social do Condomínio e Transmissão Online',
    pautas: [
      '1. Prestação de contas do exercício 2025 e parecer do Conselho Fiscal;',
      '2. Apresentação e deliberação da Previsão Orçamentária para 2026/2027;',
      '3. Eleição de Síndico, Subsíndico e Membros do Conselho Fiscal;',
      '4. Assuntos gerais de interesse coletivo.',
    ],
    publicado: true,
    criadoEm: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ass-02',
    condominioId: 'cond-01',
    titulo: 'Assembleia Geral Extraordinária - Reforma da Portaria',
    tipo: 'AGE',
    status: 'REALIZADA',
    dataHoraPrimeiraConvocacao: '2025-11-15T19:00:00',
    dataHoraSegundaConvocacao: '2025-11-15T19:30:00',
    local: 'Salão Social do Condomínio',
    pautas: [
      '1. Aprovação do projeto arquitetônico de modernização da portaria de pedestres;',
      '2. Instituição de cota extra em 6 parcelas para execução das obras.',
    ],
    ataDocumentoUrl: '#',
    publicado: true,
    criadoEm: '2025-10-20T08:00:00Z',
  },
];

export const mockAtividadesRecentes: AtividadeRecente[] = [
  {
    id: 'atv-01',
    condominioId: 'cond-01',
    usuarioNome: 'Roberto Almeida (Síndico)',
    modulo: 'COMUNICADOS',
    acao: 'Publicou novo comunicado',
    detalhes: 'Dedetização e Desratização das Áreas Comuns',
    dataHora: '2026-03-01T09:00:00Z',
  },
  {
    id: 'atv-02',
    condominioId: 'cond-01',
    usuarioNome: 'Roberto Almeida (Síndico)',
    modulo: 'FINANCEIRO',
    acao: 'Registrou despesa paga',
    detalhes: 'Portaria Remota e Monitoramento 24h - R$ 4.300,00',
    dataHora: '2026-03-01T08:45:00Z',
  },
  {
    id: 'atv-03',
    condominioId: 'cond-01',
    usuarioNome: 'Mariana Costa (Apto 204)',
    modulo: 'MANUTENCAO',
    acao: 'Abriu solicitação de manutenção',
    detalhes: 'Lâmpada queimada no hall do 2º andar - Bloco B',
    dataHora: '2026-03-01T12:45:00Z',
  },
  {
    id: 'atv-04',
    condominioId: 'cond-01',
    usuarioNome: 'Administração',
    modulo: 'DOCUMENTOS',
    acao: 'Disponibilizou documento',
    detalhes: 'Balancete Financeiro e Demonstrativo - Fevereiro/2026',
    dataHora: '2026-03-01T09:00:00Z',
  },
  {
    id: 'atv-05',
    condominioId: 'cond-01',
    usuarioNome: 'Roberto Almeida (Síndico)',
    modulo: 'MANUTENCAO',
    acao: 'Atualizou chamado para "Em Andamento"',
    detalhes: 'Revisão e regulagem do portão de veículos 01',
    dataHora: '2026-03-01T15:30:00Z',
  },
];

export const mockResumoFinanceiro: ResumoFinanceiroDashboard = {
  saldoAtual: 48920.45,
  receitasMes: 37440.0,
  despesasMes: 22150.3,
  taxaInadimplencia: 4.16, // % de unidades inadimplentes (2 de 48)
  totalInadimplente: 3120.0,
  contasVencendo7Dias: 5160.8,
  contasAtrasadas: 1560.0,
};

export const mockResumoManutencao: ResumoManutencaoDashboard = {
  abertas: 1,
  emAndamento: 1,
  concluidasMes: 4,
  urgentes: 0,
};
